interface LetterData {
  clientName: string;
  gstNumber?: string;
  content: string;
  date?: string;
  firmName?: string;
  firmAddress?: string;
  signature?: string; // Base64 data URL for digital signature
}

export async function generatePDF(letterData: LetterData): Promise<void> {
  // Dynamically import html2pdf only on client side
  const html2pdf = (await import("html2pdf.js")).default;
  
  // Format date
  const date = letterData.date || new Date().toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  // Convert content to HTML with proper line breaks
  const contentHtml = letterData.content
    .split('\n')
    .map(line => `<p style="margin: 0 0 8px 0; line-height: 1.6;">${line || '&nbsp;'}</p>`)
    .join('');

  // Create HTML content for PDF
  const htmlContent = `
    <div style="font-family: 'Noto Sans', Arial, sans-serif; padding: 40px; color: #1a1a1a; font-size: 12pt;">
      ${letterData.firmName ? `
        <div style="text-align: center; margin-bottom: 20px;">
          <h2 style="margin: 0; font-size: 18pt; color: #1a1a1a;">${letterData.firmName}</h2>
          ${letterData.firmAddress ? `<p style="margin: 5px 0; font-size: 10pt; color: #666;">${letterData.firmAddress}</p>` : ''}
          <hr style="border: none; border-top: 2px solid #10b981; margin-top: 15px;" />
        </div>
      ` : ''}
      
      <p style="margin-bottom: 20px;"><strong>Date:</strong> ${date}</p>
      
      <div style="margin-bottom: 20px;">
        <p style="margin: 0;"><strong>To,</strong></p>
        <p style="margin: 5px 0;">${letterData.clientName}</p>
        ${letterData.gstNumber ? `<p style="margin: 5px 0;">GSTIN: ${letterData.gstNumber}</p>` : ''}
      </div>
      
      <div style="margin-top: 20px;">
        ${contentHtml}
      </div>
      
      ${letterData.signature ? `
        <div style="margin-top: 30px;">
          <img src="${letterData.signature}" alt="Signature" style="max-width: 150px; height: auto;" />
        </div>
      ` : ''}
      
      <div style="margin-top: 40px; text-align: center; font-size: 8pt; color: #999;">
        Generated by GST Doc AI
      </div>
    </div>
  `;

  // Create a temporary container
  const container = document.createElement('div');
  container.innerHTML = htmlContent;
  container.style.position = 'absolute';
  container.style.left = '-9999px';
  document.body.appendChild(container);

  // Generate PDF filename
  const fileName = `GST_Letter_${letterData.clientName.replace(/\s+/g, "_")}_${new Date().toISOString().split("T")[0]}.pdf`;

  // PDF options
  const options = {
    margin: 10,
    filename: fileName,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { 
      scale: 2,
      useCORS: true,
      letterRendering: true,
    },
    jsPDF: { 
      unit: 'mm', 
      format: 'a4', 
      orientation: 'portrait' as const
    }
  };

  // Generate and download PDF
  html2pdf()
    .set(options)
    .from(container)
    .save()
    .then(() => {
      // Clean up
      document.body.removeChild(container);
    })
    .catch((error: Error) => {
      console.error("Failed to generate PDF:", error);
      document.body.removeChild(container);
    });
}
